### ISSUE TITLE
Generated Serialization code from MsgPack 0.8.0.0 is not compatible with Unity

### ISSUE THREAD

**Issue by nattawitta** [neuecc/PhotonWire#2]
I did the share class tutorial and I noticed that the generated serialization code was different with tutorial. It looked more complicated and Unity couldn't compile the code saying that it couldn't find method in MsgPack.Serialization. I figured that it was probably because of incompatible version of MsgPack. In the tutorial, the code was generated from MsgPack 0.6.0.0 But currently when installed PhotonWire from Nuget, it required MsgPack 0.8.0.0

I tried to copy this MsgPack dll and replaced the older version in Unity. I had to change Unity .NET framework to 4.6 because this dll couldn't target .NET 3.5 This caused compile error because of ambiguous using of IObservable and Tuple. The conflict was from UniRx and System. I had to modify some methods to use UniRx namespace. After doing all these, the project seem to work correctly. Client can receive serialization data from server. But I don't know if changing Unity to target .NET 4.6 will cause any problem or not. Because the tutorial is still using old dll to target .NET 3.5 for Unity.

**Comment by neuecc** [comment]
The Unity compatible version of MsgPack is here.
https://github.com/msgpack/msgpack-cli/releases
Those in this can be used with Unity (NET 3.5).
